- hosts: magento
  tasks:
    - name: Copy the docker-compose file to the node
      copy:
        src: docker-compose.yaml
        dest: /home/ubuntu
    - name: Delete the docker container
      command: docker-compose down
    - name: Start the new container
      command: docker-compose up -d
